# Generated by Django 5.1.6 on 2025-03-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=255, verbose_name='Фамилия'),
        ),
    ]
