# Generated by Django 5.1.6 on 2025-05-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_slug_product_slug_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
