# Generated by Django 5.1.6 on 2025-05-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_slug_composition_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(related_name='products', through='api.ProductAttribute', to='api.attribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='instruction_document',
            field=models.FileField(blank=True, default=None, null=True, upload_to='product_instructions/'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='api.product'),
        ),
    ]
