# Generated by Django 5.1.6 on 2025-06-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='promotion/'),
        ),
    ]
